import Head from 'next/head'

export default function Home() {
  return (
    <div className="flex h-screen">
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center font-bold text-blue-700 m-auto border shadow-md py-2 px-2 text-2xl">Learn Next JS by <span className="text-black">Muhamad Hanif Muhsin</span></div>
    </div>
  )
}
