import Head from 'next/head'

export default function Home() {
  return (
    <div className="flex h-screen">
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col m-auto border border-blue-500 py-5 px-7 shadow-md">
        <span className="text-center pb-3 text-xl">React Hook Form</span>
        <form>
          <div className="space-y-2">
            <div className="flex flex-col space-y-1">
              <label className="text-sm">Username</label>
              <input className="border border-gray-500 text-xs py-1 px-2" type="text" name="username" />
            </div>
            <div className="flex flex-col space-y-1">
              <lable className="text-sm">Password</lable>
              <input className="border border-gray-500 text-xs py-1 px-2" type="password" name="password" />
            </div>
          </div>
          <button className="bg-blue-500 mt-5 border w-full">Login</button>
        </form>
      </div>
    </div>
  )
}
